const ObjectId = require('mongoose').Types.ObjectId;


module.exports = [
 {
  "_id": new ObjectId("626737fa845438c173d97f06"),
  "title": "AWS CLOUD ONBOARDING",
  "description": "<p style=\"text-align:start;\"><span style=\"color: rgb(0,0,0);background-color: rgb(254,254,254);font-size: medium;font-family: poppins, helvetica, arial, sans-serif;\"><strong>Content:</strong></span><br><span style=\"color: rgb(0,0,0);background-color: rgb(254,254,254);font-size: medium;font-family: poppins, helvetica, arial, sans-serif;\">As a Techchak Developer, you will have to set up your development environment. This is highly recommended to avoid roadblocks while completing your projects. This is why we consider this technical onboarding your first project. Go ahead and get started.</span><br><br><span style=\"color: rgb(0,0,0);background-color: rgb(254,254,254);font-size: medium;font-family: poppins, helvetica, arial, sans-serif;\">- <strong>Install python3 on your machine:</strong> All TechChak Developers are required to install Python3 on their machine. Not because everyone will develop python scripts but because python3 is needed to install and use a virtual environment.</span><br><span style=\"color: rgb(0,0,0);background-color: rgb(254,254,254);font-size: medium;font-family: poppins, helvetica, arial, sans-serif;\"> Follow the instruction on the wiki link below to install python </span><a href=\"https://mail.zoho.com/zm/#mail/views/unread/p/1649965830223100001\" target=\"_self\"><span style=\"color: rgb(0,0,0);background-color: rgb(254,254,254);font-size: 0.875rem;font-family: poppins, helvetica, arial, sans-serif;\"><ins>https://mail.zoho.com/zm/#mail/views/unread/p/1649965830223100001</ins></span></a><br><br><span style=\"color: rgb(0,0,0);background-color: rgb(254,254,254);font-size: medium;font-family: poppins, helvetica, arial, sans-serif;\">- <strong>Install Python Virtual Environment:</strong></span> <span style=\"color: rgb(0,0,0);background-color: rgb(254,254,254);font-size: medium;font-family: poppins, helvetica, arial, sans-serif;\">A virtual environment is a Python tool that helps you manage any dependency or package you are using and also helps you Isolate your project. So instead of installing packages on your local machine, it can serve as an isolated mini-environment to quickly install your packages.</span><br><span style=\"color: rgb(0,0,0);background-color: rgb(254,254,254);font-size: medium;font-family: poppins, helvetica, arial, sans-serif;\">Follow the instruction on the wiki link below to install the virtual Environment </span><a href=\"https://mail.zoho.com/zm/#mail/views/unread/p/1649965830223100001\" target=\"_self\"><span style=\"color: rgb(0,0,0);background-color: rgb(254,254,254);font-size: 0.875rem;font-family: poppins, helvetica, arial, sans-serif;\"><ins>https://mail.zoho.com/zm/#mail/views/unread/p/1649965830223100001</ins></span></a></p>\n<p style=\"text-align:start;\"><span style=\"color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 14px;font-family: poppins, helvetica, arial, sans-serif;\"><strong>- Install Git Client: Git is software used as code source and storage. It is one of the most import important elements in the software development life cycle and useful for collaborative work among developers.</strong></span><br><span style=\"color: rgb(0,0,0);background-color: rgb(254,254,254);font-size: 14px;font-family: poppins, helvetica, arial, sans-serif;\">Follow the instruction on the wiki link below to install Git (Mac Users can Skip) </span><a href=\"https://mail.zoho.com/zm/#mail/views/unread/p/1649965830223100001\" target=\"_self\"><span style=\"color: rgb(17,85,204);background-color: rgb(254,254,254);font-size: 14px;font-family: poppins, helvetica, arial, sans-serif;\"><ins>https://mail.zoho.com/zm/#mail/views/unread/p/1649965830223100001</ins></span></a></p>\n<p style=\"text-align:start;\"><span style=\"color: rgb(0,0,0);background-color: rgb(254,254,254);font-size: medium;font-family: poppins, helvetica, arial, sans-serif;\"><strong>- Install AWS CLI:</strong> The AWS CLI also known as the Command Line Interface is a unified tool that provides a consistent interface for interacting with all parts of AWS.</span><br><span style=\"color: rgb(0,0,0);background-color: rgb(254,254,254);font-size: medium;font-family: poppins, helvetica, arial, sans-serif;\">Follow the instruction on the wiki link below to install awscli (Mac Users can Skip) </span><a href=\"https://mail.zoho.com/zm/#mail/views/unread/p/1649965830223100001\" target=\"_self\"><span style=\"color: rgb(0,0,0);background-color: rgb(254,254,254);font-size: 0.875rem;font-family: poppins, helvetica, arial, sans-serif;\"><ins>https://mail.zoho.com/zm/#mail/views/unread/p/1649965830223100001</ins></span></a><br></p>",
  "likes": [],
  "department": "cloud",
  "area": "aws infrastructure",
  "eta": 2,
  "image": "https://ds20de4grf4xk.cloudfront.net/backend-uploads/project/1650932590063_project.png",
  "level": "Beginner",
  "prerequisites": "<p style=\"text-align:start;\"><span style=\"color: rgb(0,0,0);background-color: transparent;font-size: 14px;font-family: Arial;\">- You Should have an AWS Account</span><br><span style=\"color: rgb(0,0,0);background-color: transparent;font-size: 14px;font-family: Arial;\">- Have a Working machine of at least 4GB RAM (Recommend Higher RAM for fast processing</span><br><span style=\"color: rgb(0,0,0);background-color: transparent;font-size: 14px;font-family: Arial;\">- Knowledge of Basic AWS Services</span></p>\n<p></p>",
  "hints": "<p><span style=\"font-size: 14px;\">- None</span></p>",
  "type": "personal",
  "tags": [],
  "solutions": [],
  "comments": [],
  "createdBy": "622af0006bc5509231ae69f7",
  "ratings": [new ObjectId("624dabf9aaa4af0d6e0ee12a")],
  "isVisible": true,
  "isDraft": false,
  "createdAt": "2022-04-26T00:08:26.254Z",
  "updatedAt": "2022-04-26T00:23:14.516Z",
  "__v": 0
 },
 {
  "_id": new ObjectId("62653ae127362e313d469da0"),
  "title": "Setup Your Virtual Environment",
  "description": "<p><span style=\"color: rgb(0,0,0);background-color: transparent;font-size: 10pt;font-family: Arial;\">As a Techchak Developer, you will have to set up your development environment. This is highly recommended to avoid roadblocks while completing your projects. This is why we consider this technical onboarding your first project. Go ahead and get started.</span><br></p>\n<ul>\n<li><span style=\"color: rgb(0,0,0);background-color: transparent;font-size: 10pt;font-family: Arial;\">Install python3 on your machine: All TechChak Developers are required to install Python3 on their machine. Not because everyone will develop python scripts but because python3 is needed to install and use virtual environment</span></li>\n</ul>\n<p><span style=\"color: rgb(0,0,0);background-color: transparent;font-size: 10pt;font-family: Arial;\">Follow the instruction on the wiki link below to install python .  </span><a href=\"https://mail.zoho.com/zm/#mail/views/unread/p/1649965830223100001\" target=\"_self\"><span style=\"color: rgb(17,85,204);background-color: transparent;font-size: 10pt;font-family: Arial;\"><ins>https://mail.zoho.com/zm/#mail/views/unread/p/1649965830223100001</ins></span></a><br></p>\n<ul>\n<li><span style=\"color: rgb(0,0,0);background-color: transparent;font-size: 10pt;font-family: Arial;\">Install Python Virtual Environment: </span><span style=\"color: rgb(41,41,41);background-color: rgb(255,255,255);font-size: 10pt;font-family: Arial;\">A virtual environment is a Python tool that helps you manage any dependency or package you are using and also helps you Isolate your project. So instead of installing packages on your local machine, it can serve as an isolated mini environment to quickly install your packages .  </span></li>\n</ul>\n<p><span style=\"color: rgb(0,0,0);background-color: transparent;font-size: 10pt;font-family: Arial;\">     Follow the instruction on the wiki link below to install virtual Environemnt . </span><a href=\"https://mail.zoho.com/zm/#mail/views/unread/p/1649965830223100001\" target=\"_self\"><span style=\"color: rgb(17,85,204);background-color: transparent;font-size: 10pt;font-family: Arial;\"><ins>https://mail.zoho.com/zm/#mail/views/unread/p/1649965830223100001</ins></span></a><br></p>\n<ul>\n<li><span style=\"color: rgb(41,41,41);background-color: rgb(255,255,255);font-size: 10pt;font-family: Arial;\">Install Git Client: Git is a software used as code source and storage. It is one of the most import important element in software development lify cycle and useful for collaborative wokr among developers.</span></li>\n</ul>\n<p><span style=\"color: rgb(0,0,0);background-color: transparent;font-size: 10pt;font-family: Arial;\">      Follow the instruction on the wiki link below to install Git (Mac Users can Skip) </span><a href=\"https://mail.zoho.com/zm/#mail/views/unread/p/1649965830223100001\" target=\"_self\"><span style=\"color: rgb(17,85,204);background-color: transparent;font-size: 10pt;font-family: Arial;\"><ins>https://mail.zoho.com/zm/#mail/views/unread/p/1649965830223100001</ins></span></a><br></p>\n<ul>\n<li><span style=\"color: rgb(41,41,41);background-color: rgb(255,255,255);font-size: 10pt;font-family: Arial;\">Install AWSCLI: The AWS also know as the Command Line Interface is a unified tool that provides a consistent interface for interacting with all parts of AWS.</span></li>\n</ul>\n<p><span style=\"color: rgb(0,0,0);background-color: transparent;font-size: 10pt;font-family: Arial;\">     Follow the instruction on the wiki link below to install awscli (Mac Users can Skip) </span><a href=\"https://mail.zoho.com/zm/#mail/views/unread/p/1649965830223100001\" target=\"_self\"><span style=\"color: rgb(17,85,204);background-color: transparent;font-size: 10pt;font-family: Arial;\"><ins>https://mail.zoho.com/zm/#mail/views/unread/p/1649965830223100001</ins></span></a><br></p>\n<ul>\n<li><span style=\"color: rgb(41,41,41);background-color: rgb(255,255,255);font-size: 10pt;font-family: Arial;\">Install a Code Editor of your choice:</span></li>\n</ul>",
  "likes": [],
  "department": "cloud",
  "area": "aws infrastructure",
  "eta": 2,
  "image": "https://ds20de4grf4xk.cloudfront.net/backend-uploads/project/1650801476699_project.jpeg",
  "level": "Intermediate",
  "prerequisites": "<ul>\n<li><span style=\"color: rgb(0,0,0);background-color: transparent;font-size: 10pt;font-family: Arial;\">You Should have an AWS Account</span></li>\n<li><span style=\"color: rgb(0,0,0);background-color: transparent;font-size: 10pt;font-family: Arial;\">Have a Working machine of at least 4GB RAM (Recommend Higher RAM for fast processing)</span></li>\n<li><span style=\"color: rgb(0,0,0);background-color: transparent;font-size: 10pt;font-family: Arial;\">Knowledge of Basic AWS Services</span></li>\n</ul>",
  "hints": "<p>NONE</p>",
  "type": "personal",
  "tags": [],
  "solutions": [],
  "comments": [],
  "createdBy": "622af0006bc5509231ae69f7",
  "ratings": [new ObjectId("624db238b239569442a3f22b")],
  "isVisible": true,
  "isDraft": false,
  "createdAt": "2022-04-24T11:56:17.925Z",
  "updatedAt": "2022-04-24T11:57:56.851Z",
  "__v": 0
 }, 
 {
  "_id": new ObjectId("625ca9e770edb907135e0a6c"),
  "title": "SET UP YOUR COMPANY'S INFRASTRUCTURE USING CLOUDFORMATION",
  "description": "<p>Techchak wants to deploy a webserver used to run some daily crojobs in AWS and we don't want to deploy the server into default VPC, subnets, security groups or routes. We will like to provision our custome resources. We need you to help us make this happen. We also prefer it done via Infrastructure as code (Specificallly Cloudformation). This is because this enables for stable, consistent and easilty modifiable infrastructure and also allows for easy resusabiulity.&nbsp;</p>\n<p>Once you are able to successfully do the above, try doing the same using AWS CLI<br>To deploy with aws cli, dont forget you need install aws cli (First activate virtual environment). After this, do your aws configure, then enter your secret and access key. Once you finish this, you should go online and find the AWS CLI command to create stack . RUn on your local machine and try again.</p>\n<p>Do not forget to always provide a detailed architecture for your work</p>",
  "likes": [],
  "department": "cloud",
  "area": "aws infrastructure",
  "eta": 3,
  "image": "https://ds20de4grf4xk.cloudfront.net/backend-uploads/project/1650239975662_project",
  "level": "Intermediate",
  "prerequisites": "<ul>\n<li><span style=\"color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: medium;font-family: poppins, helvetica, arial, sans-serif;\">You should know the basics of cloudformation You can find a great reference   </span><a href=\"https://docs.aws.amazon.com/codebuild/latest/userguide/cloudformation-vpc-template.html\" target=\"_blank\"><span style=\"color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 0.875rem;font-family: poppins, helvetica, arial, sans-serif;\">here</span></a>&nbsp;</li>\n<li>Install awscli on your machine. You can find how to her</li>\n<li>Knowledge of AWS VPC</li>\n</ul>\n<p></p>",
  "hints": "<ol>\n<li>Create an empty Gitlab Repo and within the Repo, create a file named infra-template.yaml]</li>\n<li>Clone this repo into your local directory</li>\n<li>Once you have cloned you repo to your local machine successfully, You will modify infra-template.yaml file to  create the following resources</li>\n</ol>\n<ul>\n<li>VPC</li>\n<li>Private subnet</li>\n<li>Public subnet</li>\n<li>Route tables (public, private)</li>\n<li>Internet Gateway</li>\n<li>Security Group</li>\n<li>Ingress rules for the SG group</li>\n</ul>\n<p><span style=\"color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: medium;font-family: poppins, helvetica, arial, sans-serif;\">Once you are confident try to deploy via the console by logging into your AWS Account, going to cloudformstion servide, create new stack and choose to upload your template from local machine by selecting the infra-template.yaml file you upodated<br>Make sure the above deploys successfully. You might get errors but do not give up. Keep reading the cause of your errors, delete the stack and recreate again until you get success<br></span></p>",
  "type": "personal",
  "tags": [],
  "solutions": [],
  "comments": [],
  "participants": [],
  "createdBy": "622af0006bc5509231ae69f7",
  "ratings": [new ObjectId("624dcbf9aaa4af0d6e0ee12c")],
  "createdAt": "2022-04-17T23:59:35.735Z",
  "updatedAt": "2022-04-27T20:59:56.361Z",
  "__v": 7,
  "isDraft": false,
  "isVisible": true
 },
 {
  "isVisible": true,
  "isDraft": false,
  "_id": new ObjectId("625ca39570edb907135e0a4b"),
  "title": "EXCHANGE RATE API JOB SCHEDULING",
  "description": "<p>I am starting an Exchange Company, and I want to get the rate at which exchange rate fluctuates from USD to (insert your currency of choice) <br>I want to get and export of the exchange rate as a JSON output every hour into an S3 bucket. <br>I also want to be notified if there is any type of failure during the job process. <br>Below are the services that will be leveraged in this project</p>",
  "likes": [],
  "department": "cloud",
  "area": "aws infrastructure",
  "eta": 3,
  "image": "https://ds20de4grf4xk.cloudfront.net/backend-uploads/project/1650238356969_project",
  "level": "Intermediate",
  "prerequisites": "<p>Below are the services that will be leveraged in this project:</p>\n<ul>\n<li>EC2: Responsible for running a python script that will generate exchange rates and write the output into a JSON file and send that JSON file into s3(this must be done hourly)</li>\n<li>S3, JSON files of the exchange rate will be stored into an s3 bucket.</li>\n<li>IAM, EC2 will need permission to write into the bucket where exchange rate JSON files will be stored.</li>\n<li>SNS, we will be sending a job failure or job success notification to the exchange team each time I successfully write into the bucket or each time the jobs fails.</li>\n<li>JOB failure will mean error encountered in the process any point in time.</li>\n</ul>",
  "hints": "<p>Below is the python code that generated the exchange rate data. Copy this code and save inside a .py file that will sit in your ec2<br>Trigger the python script with a bash script</p>\n<p>&nbsp;&nbsp;&nbsp;<code> import forex_python</code></p>\n<p><code>    from forex_python.converter </code></p>\n<p><code>    import CurrencyRates</code></p>\n<p><code>    c = CurrencyRates()    </code></p>\n<p><code>    print(c.get_rates('USD'))</code></p>\n<p>More Context<br>In the past, what developers have done is created an ec2 instance, ssh into the instance and do the followind</p>\n<ul>\n<li>Create a director named \"exchange\"</li>\n<li>go into the directory and create two more directories (scripts and dataoutput)</li>\n<li>scripts directory should have 2 files</li>\n<ul>\n<li>exchange_rate.py file (containing the python script above that fetchtes the exchange rate)</li>\n<li>run_exchange.sh file (a bash script that will trigger the python script above)</li>\n</ul>\n<li>Also a cron job will be created in the same server. This cron job will do the hourly run for you (Do your research on how to set the cronjob)</li>\n</ul>\n<p>Below is the python code that generated the exchange rate data. Copy this code and save inside a .py file that will sit in your ec2<br></p>",
  "type": "personal",
  "tags": [],
  "solutions": [],
  "comments": [],
  "participants": [],
  "createdBy": "622af0006bc5509231ae69f7",
  "ratings": [new ObjectId("624de238b239569442a3f481")],
  "createdAt": "2022-04-17T23:32:37.045Z",
  "updatedAt": "2022-04-17T23:32:37.045Z",
  "__v": 0
 },
 {
  "isVisible": true,
  "isDraft": false,
  "_id": new ObjectId("625c948f70edb907135e0936"),
  "title": "AWS Config & PROGRAMATIC REMEDIATION",
  "description": "<p>Your Senior Management is concerned about engineers creating unencrypted S3 buckets and uploading unencrypted objects into S3 buckets. They want you to track situations like this and if you find any, they want to remediate them using Lambda. After the remediation is complete, they want you to send a notification to the security department about which buckets were remediated. <br>You determine what your Lambda function should do.<br>Your solution should:</p>\n<ul>\n<li>&nbsp;A. Detect any unencrypted S3 Buckets (Hint: Use AWS Config)</li>\n<li>&nbsp;B. Remediate the bucket(s) and make them encrypted.</li>\n<li>&nbsp;C. Send an SNS notifcation of which bucket(s) were remediated.</li>\n</ul>",
  "likes": [],
  "department": "cloud",
  "area": "aws security",
  "eta": 4,
  "image": "https://ds20de4grf4xk.cloudfront.net/backend-uploads/project/1650234511588_project",
  "level": "Beginner",
  "prerequisites": "<p>- have aws account</p>",
  "hints": "<p>&nbsp;A. Detect any unencrypted S3 Buckets (Hint: Use AWS Config)</p>\n<p>&nbsp;B. Remediate the bucket(s) and make them encrypted.</p>\n<p>C. Send an SNS notifcation of which bucket(s) were remediated.</p>",
  "type": "personal",
  "tags": [],
  "solutions": [],
  "comments": [],
  "participants": [],
  "createdBy": "622af0006bc5509231ae69f7",
  "ratings": [new ObjectId("624dfbf9aaa4af0d6e0fe12d")],
  "createdAt": "2022-04-17T22:28:31.687Z",
  "updatedAt": "2022-04-17T22:38:23.338Z",
  "__v": 1
 }
]