const ObjectId = require('mongoose').Types.ObjectId,
  superAdmin = require("./superAdmin"),
  projectId = new ObjectId(),
  commentIds = [new ObjectId("624d9bf9aaa4af0d6e0ee44a"), new ObjectId("624da238b239569442a3f58f")],
  ratingsId = [
    new ObjectId("624d9bf9aaa4af0d6e0ee12a"),
    new ObjectId("624da238b239569442a3f22b"),
    new ObjectId("624d9bf9aaa4af0d6e0ee12c"),
    new ObjectId("624da238b239569442a3f481"),
    new ObjectId("624d9bf9aaa4af0d6e0fe12d"),
  ];


  const cloudProjects = require("./cloud_projects.js");
const projects = [
  // {
  //   _id: new ObjectId("624d9bf9aaa4af0d5e0ee14a"),
  //   title: "Create a static landing page",
  //   image: "https://res.cloudinary.com/remilekunelijah/image/upload/v1648210490/dqnlw70ls4dbjzqrglwp.png",
  //   description: "<p>This is a project for beginner</p>",
  //   likes: [],
  //   department: "software development",
  //   area: "backend",
  //   eta: 3,
  //   level: "Intermediate",
  //   prerequisites: "1. Knowledge of programming languages (HTML) ...",
  //   hints: "Hello world, hi there, we are building a robot",
  //   type: "personal",
  //   tags: ['Nodejs', 'APIs'],
  //   solutions: [],
  //   comments: [],
  //   // participants: [],
  //   createdBy: superAdmin.profile._id,
  //   ratings: [ratingsId[0]],
  //   isVisible: true,
  //   isDraft: false,

  //   createdAt: "2022-04-04T14:30:09.301+00:00",
  //   updatedAt: "2022-04-08T13:59:01.584+00:00"
  // },
  // {
  //   _id: new ObjectId("614d7bf9aaa4af0d5e0ee11a"),
  //   title: "Create a javascript BE library",
  //   image: "https://res.cloudinary.com/remilekunelijah/image/upload/v1648210473/vahidimtl8sm9anq2qlp.png",
  //   description: "<p>Build a backend library hosted on a static site generator</p>",
  //   likes: [],
  //   department: "software development",
  //   area: "backend",
  //   eta: 4,
  //   level: "Intermediate",
  //   prerequisites: "1. Knowledge of programming languages (HTML) ...",
  //   hints: "Hello world, hi there, we are building a robot",
  //   type: "personal",
  //   tags: [],
  //   solutions: [],
  //   comments: [],
  //   // participants: [],
  //   createdBy: superAdmin.profile._id,
  //   ratings: [ratingsId[1]],
  //   isVisible: true,
  //   isDraft: false,
  //   createdAt: "2022-04-04T14:30:09.301+00:00",
  //   updatedAt: "2022-04-08T13:59:01.584+00:00"
  // },
  // {
  //   _id: new ObjectId("624b00f18960a3f65f166a86"),
  //   title: "Robotics With JS",
  //   image: "https://res.cloudinary.com/remilekunelijah/image/upload/v1646904730/algnlqsiroh1xp91pumh.png",
  //   description: "<p>This sis is a robotic application hope you know</p>",
  //   likes: [],
  //   department: "software development",
  //   area: "backend",
  //   eta: 9,
  //   level: "Intermediate",
  //   prerequisites: "1. Knowledge of programming languages (HTML) ...",
  //   hints: "Hello world, hi there, we are building a robot",
  //   type: "personal",
  //   tags: [],
  //   solutions: [],
  //   comments: [commentIds[0]],
  //   // participants: [new ObjectId("6250af19437b0c758ea91caf")],
  //   createdBy: superAdmin.profile._id,
  //   ratings: [ratingsId[2]],
  //   isVisible: true,
  //   isDraft: false,
  //   createdAt: "2022-04-04T14:30:09.301+00:00",
  //   updatedAt: "2022-04-08T13:59:01.584+00:00"
  // },
  // {
  //   _id: new ObjectId("624ae15c8960a3f65f166a0c"),
  //   title: "Create Node REST API",
  //   image: "https://res.cloudinary.com/remilekunelijah/image/upload/v1646079511/b3nhzjmchccoxxaasamz.png",
  //   description: "<p>Create a nodejs rest api with javascript and expressjs using mongodb as a data store.</p>",
  //   likes: [new ObjectId("6250af19437b0c758ea91caf")],
  //   department: "software development",
  //   area: "backend",
  //   eta: 3,
  //   level: "Intermediate",
  //   prerequisites: "1. Knowledge of programming languages (JAVASCRIPT), (API) and (MONGODB)...",
  //   hints: "Hello world, hi there, we are building a robot",
  //   type: "personal",
  //   tags: ["NODEJS", "EXPRESSJS", "MONGODB"],
  //   solutions: [],
  //   comments: [commentIds[1]],
  //   createdBy: superAdmin.profile._id,
  //   ratings: [ratingsId[3]],
  //   isVisible: true,
  //   isDraft: false,
  //   createdAt: "2022-04-04T14:30:09.301+00:00",
  //   updatedAt: "2022-04-08T13:59:01.584+00:00"
  // },
  // {
  //   _id: projectId,
  //   title: "Create BIG DATA API",
  //   image: "https://res.cloudinary.com/remilekunelijah/image/upload/v1524646544/sample.jpg",
  //   description: "<p>Create a big data api with python and flask using postresql as a data store.</p>",
  //   likes: [new ObjectId("6250af19437b0c758ea91caf")],
  //   department: "software development",
  //   area: "backend",
  //   eta: 60,
  //   level: "Intermediate",
  //   prerequisites: "1. Knowledge of programming languages (JAVASCRIPT), (API) and (MONGODB)...",
  //   hints: "Hello world, hi there, we are building a robot",
  //   type: "capstone",
  //   tags: ["NODEJS", "EXPRESSJS", "MONGODB"],
  //   solutions: [],
  //   comments: [],
  //   createdBy: superAdmin.profile._id,
  //   ratings: [ratingsId[4]],
  //   isVisible: false,
  //   createdAt: "2022-04-04T14:30:09.301+00:00",
  //   updatedAt: "2022-04-08T13:59:01.584+00:00"
  // },
  ...cloudProjects
]

module.exports = {
  projects,
  createdBy: superAdmin.profile._id,
  commentIds
}